# Generated by Django 3.1.6 on 2021-02-11 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackingapi', '0002_auto_20210211_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='vacation_date',
            new_name='vacation_end_date',
        ),
        migrations.AddField(
            model_name='vacation',
            name='vacation_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
