# Generated by Django 3.1.6 on 2021-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackingapi', '0004_auto_20210212_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_types',
            field=models.CharField(choices=[('ARRIVAL', 'Arrival'), ('LEAVE', 'Leave'), ('NONE', 'None')], default='NONE', max_length=10),
        ),
    ]
