# Generated by Django 3.1.6 on 2021-02-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetrackingapi', '0005_check_check_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='check_types',
        ),
    ]
