# Generated by Django 3.1.6 on 2021-02-15 23:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetrackingapi', '0006_remove_check_check_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='check_choices',
        ),
        migrations.AddField(
            model_name='check',
            name='check_choice',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='checked_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
